# Generated by Django 5.1.1 on 2024-09-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityname', models.CharField(max_length=50)),
                ('collegename', models.CharField(max_length=300)),
                ('branch', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('passion', models.CharField(max_length=200)),
                ('fk_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.student')),
            ],
        ),
    ]
