# Generated by Django 5.1.1 on 2024-09-21 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='fk_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='portfolioApp.student'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=250)),
                ('companyaddr', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=200)),
                ('projectdescription', models.TextField()),
                ('usedskills', models.CharField(max_length=500)),
                ('fk_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_details', to='portfolioApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=150)),
                ('fk_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_details', to='portfolioApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatedskills', models.TextField()),
                ('fk_Skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_details', to='portfolioApp.skills')),
            ],
        ),
    ]
