# Generated by Django 5.1.1 on 2024-10-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=1000)),
                ('usedSkills', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
