# Generated by Django 5.1.1 on 2024-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skills_logo',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
