# Generated by Django 5.1.1 on 2024-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_skills_skills_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='name',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
